#!/bin/bash

# Setup X11 forwarding
if read proto cookie && [ -n "$DISPLAY" ]; then
  if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add unix:`echo $DISPLAY |
    cut -c11-` $proto $cookie
  else
    # X11UseLocalhost=no
    echo add $DISPLAY $proto $cookie
  fi | xauth -q -
fi

# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK"; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock.$(hostname)
fi

# GPG forwarding
GNUPG_GPGCONF=gpgconf
if [[ -f ~/.local/bin/gpgconf ]]; then
  GNUPG_GPGCONF=~/.local/bin/gpgconf
fi
GNUPG_AGENT_SOCKET=$($GNUPG_GPGCONF --list-dirs | grep agent-socket)
GNUPG_AGENT_SOCKET=${GNUPG_AGENT_SOCKET//agent-socket:/}
if [[ ! -S "$GNUPG_AGENT_SOCKET" ]]; then
  GNUPG_FORWARDED_SOCKET="/tmp/$(id -un)/S.gpg-agent"
  if [[ ! -S "$GNUPG_FORWARDED_SOCKET" ]]; then
    echo "Warning: GPG socket invalid!"
  else
    [[ ! -d "/run/user/$(id -u)/gnupg" ]] && $GNUPG_GPGCONF --create-socketdir
    [[ ! -L $GNUPG_AGENT_SOCKET ]] && ln -s "$GNUPG_FORWARDED_SOCKET" "$GNUPG_AGENT_SOCKET"
  fi
fi
