#!/bin/bash

# Setup X11 forwarding
if read proto cookie && [ -n "$DISPLAY" ]; then
  if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add unix:`echo $DISPLAY |
    cut -c11-` $proto $cookie
  else
    # X11UseLocalhost=no
    echo add $DISPLAY $proto $cookie
  fi | xauth -q -
fi

# Fix SSH auth socket location so agent forwarding works with tmux
if test "$SSH_AUTH_SOCK"; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock.$(hostname)
fi

# gnupg
GNUPG_AGENT_SOCKET=$(gpgconf --list-dirs | grep agent-socket)
GNUPG_AGENT_SOCKET=${GNUPG_AGENT_SOCKET//agent-socket:/}
[[ ! -d "/run/user/$(id -u)/gnupg" ]] && gpgconf --create-socketdir
[[ ! -L $GNUPG_AGENT_SOCKET ]] && ln -s "/tmp/$(id -un)/S.gpg-agent" "$GNUPG_AGENT_SOCKET"
